server:
  port: 9090

keycloak:
  realm: IEIMS
  bearer-only: true
  auth-server-url: http://localhost:8000/auth
  ssl-required: external
  resource: api-2
  verify-token-audience: true
  use-resource-role-mappings: true
  confidential-port: 0
  principal-attribute: preferred_username

logging:
  level:
    ieims.api2: debug
    org.keycloak: debug
