server:
  port: 9090

keycloak:
  realm: IEIMS
  bearer-only: true
  auth-server-url: http://localhost:8000/auth
  ssl-required: external
  resource: api-2
  use-resource-role-mappings: false
  confidential-port: 0
  principal-attribute: preferred_username
  credentials:
    secret: cJDypObD319RU4dqJpbBbmwaXFQRnVnZ

logging:
  level:
    ieims.api2: debug
    org.keycloak: debug
