server:
  port: 7070
  servlet:
    session:
      cookie:
        name: JSESSIONID
        path: /
        http-only: false

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: "api-3"
            client-name: "api-3"
            client-secret: "2652a05c-3b87-4a2e-9941-36428f3b2176"
            provider: "keycloak"
        provider:
          keycloak:
            issuer-uri: "http://localhost:8000/auth/realms/development"
            #authorization-uri: http://localhost:8000/auth/realms/demo/protocol/openid-connect/auth
            #token-uri: http://localhost:8000/auth/realms/demo/protocol/openid-connect/token
            #user-info-uri: http://localhost:8000/auth/realms/demo/protocol/openid-connect/userinfo
            jwk-set-uri: "http://localhost:8000/auth/realms/development/protocol/openid-connect/certs"
            #user-name-attribute: preferred_username

successUrl:  http://localhost:4000

