keycloak:
  realm: development
  bearer-only: true
  auth-server-url: http://localhost:8000/auth
  ssl-required: external
  resource: api-1
  verify-token-audience: true
  use-resource-role-mappings: true
  confidential-port: 0
  principal-attribute: preferred_username

logging:
  level:
    ieims.api1: debug
