keycloak:
  realm: IEIMS
  bearer-only: true
  auth-server-url: http://localhost:8000/auth
  ssl-required: external
  resource: api-1
  use-resource-role-mappings: false
  confidential-port: 0
  principal-attribute: preferred_username
  credentials:
    secret: 78FIbGw1FwtpOnryp9ULMRkt4eO2hFzl

logging:
  level:
    ieims.api1: debug
    org.keycloak: debug
server:
  port: 8888


